### ISSUE TITLE
Tmodloader

### ISSUE THREAD

**Issue by Nexow91** [jasperfirecai2/amp-templates#8]
Hi im try to running tmodloader on AMP 1.4x and im upload modconfig files like .json it doesnt works. 
The server didnt load my local edit config on amp software ? need amp another path or its not works actually global from amp ?

**Comment by jasperfirecai2** [comment]
Hi, please visit the official AMP discord or forums for more specific guidance. I am not affiliated with AMP, just a small open source contributor. 
regardless,
As far as we know, there's no way to change where the server saves its mod config files. There is currently no feature in the AMP template to assist with configuration.  Please see https://github.com/jasperfirecai2/amp-templates/wiki/Managing-mods-with-tmodloader#mod-configurations for reference. I will be closing this issue. please reach out on any of AMPs official channels for full support
